server:
  port: 8888
  servlet:
    session:
      timeout: 20m
spring:
  profiles:
    active: dev
  application:
    name: util
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: html
    favicon:
      enabled: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      maxFileSize: 25MB

  datasource:
#    druid:
      driver-class-name: ${album.datasource.driver-class-name}
      url: jdbc:mysql://${album.datasource.host}:${album.datasource.port}/${album.datasource.database}?serverTimezone=CTT&useSSL=false
      username: ${album.datasource.username}
      password: ${album.datasource.password}

#  datasource:
#    url: jdbc:mysql://localhost:3306/album?serverTimezone=CTT&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true

OSS:
  endpoint: ""
  accessKeyId: ""
  accessKeySecret: ""
  bucketName: ""